---
deployment:
  tasks:
    - export COMPOSER_HOME=~/.cpanel/composer
    - /opt/cpanel/composer/bin/composer install --no-ansi --no-interaction --optimize-autoloader --no-progress --no-scripts
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan route:cache
    - php artisan view:cache
    - php artisan migrate --force
